---

cookieconsent_banner_type: headline
cookieconsent_consent_type: express
cookieconsent_palette: light
cookieconsent_language: en
cookieconsent_href: 'https://cookiesandyou.com/'
enable_cookie_agreement: 0
enable_terms: 0
last_terms_reset: ''
terms_page: ''
terms_project_id: ''
terms_reject_page: ''
terms_reject_project_id: ''
